### ISSUE TITLE
GCode throws error: toolchange_count is not a variable name

### ISSUE THREAD

**Issue by ChristianPrei** [eukatree/Bambu_CustomGCode#9]
Bambu Studio Version 1.9.1.66 throws the following error:

`filament_start_gcode Parsing error at line 11: Not a variable name
{if toolchange_count > 1}
    ^`

Printer: A1 Mini
I used this code: 
* Branch: A1_mini_0.4_mm_nozzle
* Directory [A1_Mini](https://github.com/eukatree/Bambu_CustomGCode/tree/A1_mini_0.4_mm_nozzle/A1_Mini)
* File: change_filament_no_AMS_A1_mini_0.4nozzle.gcode

![grafik](https://github.com/eukatree/Bambu_CustomGCode/assets/57258042/5fb065de-12c1-497a-b82c-06199a1e2ffc)

**Comment by eukatree** [comment]
The custom g code needs to go into the "Change Filament" g code section. It looks like you've put it into the "Filament Start" g code section.
